-- Jalankan file ini di Supabase SQL Editor untuk menyamakan tabel dengan aplikasi.
-- Catatan: policy write publik cocok untuk demo/proyek kampus dengan admin password di client.
-- Untuk produksi, sebaiknya pindahkan fitur admin ke Supabase Auth atau server-side API.

create table if not exists public.berita (
  id bigint generated by default as identity primary key,
  judul text not null,
  kategori text not null,
  waktu text not null,
  image text,
  isi text not null,
  likes integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.berita
  add column if not exists judul text,
  add column if not exists kategori text,
  add column if not exists waktu text,
  add column if not exists image text,
  add column if not exists isi text,
  add column if not exists likes integer default 0,
  add column if not exists created_at timestamptz default now();

update public.berita
set likes = 0
where likes is null;

update public.berita
set created_at = now()
where created_at is null;

alter table public.berita
  alter column likes set default 0,
  alter column likes set not null,
  alter column created_at set default now(),
  alter column created_at set not null;

alter table public.berita enable row level security;

drop policy if exists "Berita bisa dibaca publik" on public.berita;
create policy "Berita bisa dibaca publik"
on public.berita
for select
to anon, authenticated
using (true);

drop policy if exists "Berita bisa ditambah publik" on public.berita;
create policy "Berita bisa ditambah publik"
on public.berita
for insert
to anon, authenticated
with check (true);

drop policy if exists "Berita bisa diedit publik" on public.berita;
create policy "Berita bisa diedit publik"
on public.berita
for update
to anon, authenticated
using (true)
with check (true);

drop policy if exists "Berita bisa dihapus publik" on public.berita;
create policy "Berita bisa dihapus publik"
on public.berita
for delete
to anon, authenticated
using (true);
